"""
Generates static JSON API files from FMED TSV data and integrates PR8 reference sequences.
"""

import json
import os
import csv
from collections import defaultdict
from datetime import datetime

DATA_TSV = "docs/parsed_issues.tsv"
DOI_TSV = "docs/validated_dois.tsv"
API_DIR = "docs/api"

def load_tsv(file_path):
    if not os.path.exists(file_path):
        return []
    with open(file_path, "r", encoding="utf-8") as f:
        return list(csv.DictReader(f, delimiter="\t"))

def main():
    os.makedirs(os.path.join(API_DIR, "protein"), exist_ok=True)
    
    mutations = load_tsv(DATA_TSV)
    dois = load_tsv(DOI_TSV)
    
    # Map DOI metadata for easy lookup
    doi_map = {}
    for row in dois:
        key = (row['protein'], row['mutation'], row['source_publication'])
        doi_map[key] = {
            "authors": row.get("Authors", ""),
            "year": row.get("Year", ""),
            "title": row.get("Title", ""),
            "journal": row.get("Journal", ""),
            "doi_url": row.get("DOI_URL", "")
        }

    # Process all mutations
    api_data = []
    protein_data = defaultdict(list)
    
    for m in mutations:
        key = (m['protein'], m['mutation'], m['source_publication'])
        entry = {
            "protein": m['protein'],
            "mutation": m['mutation'],
            "reference_accession": m['reference_accession'],
            "effect": m['effect'],
            "doi": m['source_publication'],
            "notes": m['notes'],
            "metadata": doi_map.get(key, {})
        }
        api_data.append(entry)
        protein_data[m['protein']].append(entry)

    # Save all.json
    with open(os.path.join(API_DIR, "all.json"), "w") as f:
        json.dump(api_data, f, indent=2)

    # Save protein-specific JSONs
    for protein, data in protein_data.items():
        if protein and protein != "Unknown":
            with open(os.path.join(API_DIR, "protein", f"{protein}.json"), "w") as f:
                json.dump(data, f, indent=2)

    # Save sequences.json (PR8 Reference)
    # Using sequences from Influenza Research Database / UniProt for PR8
    sequences = {
        "HA": "MKAKLLVLLCTFTATYADTICIGYHANNSTDTVDTVLEKNVTVTHSVNLLEDSHNGKLCRLKGIAPLQLGKCNIAGWLLGNPECDPLLPVRSWSYIVETPNSENGICYPGDFIDYEELREQLSSVSSFERFEIFPKESSWPNHNTNGVTAACSHEGKSSFYRNLLWLTEKEGSYPKLKNSYVNKKGKEVLVLWGIHHPSTSADQQSLYQNADAYVFVGSSRYSKKFKPEIAIRPKVRDQEGRMNYYWTLVEPGDKITFEATGNLVVPRYAFAMERNAGSGIIISDTPVHDCNTTCQTPKGAINTSLPFQNIHPITIGKCPKYVKSTKLRLATGLRNVPSIIDR",
        "NA": "MNPNQKIITIGSICMVVGIISLILQIGNIISIWVSHSIQTGNQHQIETCNQSVITYENNTWVNQTYVNISNTNFAAGQSVVSVKLAGNSSLCPVSGWAIYSKDNSVRIGSKGDVFVIREPFISCSPLECRTFFLTQGALLNDKHSNGTVKDRSPYRTLMSCPVGEAPSPYNSRFESVAWSASACHDGMGWLTIGISGPDNGAVAVLKYNGIITDTIKSWRNNILRTQESECACVNGSCFTIMTDGPSDGLASYKIFKIEKGKVTKSIELNAPNYHYEECSCYPDTGKVMCVCRDNWHGSNRPWVSFDQNLDYQIGYICSGVFGDNPRPKDGTGSCGPVYVDGANGVKGFSYRYGNGVWIGRTKSHSSRHGFEMIWDPNGWTETDSKFSVRQDVVAMTDWSGYSGSFVQHPELTGLDCIRPCFWVELIRGRPKESTIWTSGSSISFCGVNSDTVGWSWPDGAELPFTIDK",
        "PB2": "MERIKELRNLMSQSRTREILTKTTVDHMAIIKKYTSGRQEKNPALRMKWMMAMKYPITADKRIMEMIPERNEQGQTLWSKTNDAGSDRVMVSPLAVTWWNRNGPMTSTVHYPKVYKTYFEKVERLKHGTFGPVHFRNQVKIRRRVDINPGHADLSAKEAQDVIMEVVFPNEVGARILTSESQLTITKEKKEELQDCKIAPLMVAYMLERELVRKTRFLPVAGGTSSVYIEVLHLTQGTCWEQMYTPGGEVRNDDVDQSLIIAARNIVRRAAVSADPLASLLEMCHSTQIGGTRMVDILRQNPTEEQAVDICKAAMGLRISSSFSFGGFTFKRTSGSSVKKEEEVLTGNLQTLKIRVHEGYEEFTMVGRRATAILRKATRRLIQLIVSGRDEQSIAEAIIVAMVFSQEDCMIKAVRGDLNFVNRANQRLNPMHQLLRHFQKDAKVLFQNWGIEPIDNVMGMIGILPDMTPSTEMSLRGVRVSKMGVDEYSSTERVVVSIDRFLRVRDQRGNVLLSPEEVSETQGTEKLTITYSSSMMWEINGPESVLVNTYQWIIRNWETVKIQWSQNPTMLYNKMEFEPFQSLVPKAIRGQYSGFVRTLFQQMRDVLGTFDTTQIIKLLPFAAAPPKHSRMQFSSLTVNVRGSGLRILVRGNSPVFNYNKATKRLTVLGKDAGALTEDPDEGTAGVESAVLRGFLILGKEDRRYGPALSINELSNLAKGEKANVLIGQGDVVLVMKRKRDSSILTDSQTATKRIRMAIN",
        "PB1": "MDVNPTLLFLKVPAQNAISTTFPYTGDPPYSHGTGTGYTMDTVNRTHQYSEKGKWTTNTETGAPQLNPIDGPLPEDNEPSGYAQTDCVLEAMAFLEESHPGIFENSCLETMEVVQQTRVDKLTQGRQTYDWTLNRNQPAATALANTIEVFRSNGLTANESGRLIDFLKDVMESMDKEEMEITTHFQRKRRVRDNMTKKMVTQRTIGKKKQRVNKRSYLIRALTLNTMTKDAERGKLKRRAIATPGMQIRGFVYFVETLARSICEKLEQSGLPVGGNEKKAKLANVVRKMMTNSQDTELSFTITGDNTKWNENQNPRMFLAMITYITKNQPEWFRNILSIAVIMFSVVRTLGKGYMFESKRMKIRTQIPAEKMLPSTFDAMEYLNKSIPEMKIYSEDVETLRTLLRMEESITRNSGLINTDLTGLMVVALTREKLIKIRATKRTREIVIKRGGRGVGQTTGTISSETITSITREVVLNVKIRTGGVPLVVLKSRLKQLLKVTTSIVMILGSLTKSSKRVSGSPQEARELTRIPMLISKVSENVKVKALLLRFSVEIVMSGSSRGLSNINLINGSDIGVKLDKNRCSPKLQGTFDLSS",
        "PA": "MEDFVRQCFNPMIVELAEKAMKEYGEDLKIETNKFAAICTHLEVCFMYSDFHFIDERGESIIVESGDPNALLKHRFEIIEGRDRTMAWTVVNSICNTTGVEKPKFLPDLYDYKENRFIEIGVTRREVHIYYLEKANKIKSEKTHIHIFSFTGEEMATKADYTLDEESRARIKTRLFTIRQEMASRGLWDSFRQSERGEETIEEKFEITGTMRKLADQSLPPNFSSLENFRAYVDGFEPNGCIEGKLSQMSKEVNAKIEPFLKTTPRPLRLPDGPPCSQRSKFLLMDALKLSIEDPSHEGEGIPLYDAIKCMKTFFGWKEPNIVKPHEKGINPNYLLAWKQVLAELQDIENEEKIPKTKNMRKTSQLKWALGENMAPEKVDFEDCKDVSDLKQYDSDEPELRSLSSWIQNEFNKACELTDSSWIELDEIGEDVAPIEHIASMRRNYFTAEVSHCRATEYIMKGVYINTALLNASCAAMDEFGFTKIPMVSKCIKREEKGGWMKQNRNGLRNVLLRDQSVPNEAFWKFIEKRYMVVIGYLLSVLMGLKRIKALSNKVIAVVEGSFFTGEFKSTN",
        "NP": "MASQGTKRSYEQMETDGERQNATEIRASVGKMIGGIGRFYIQMCTELKLSDYEGRLIQNSLTIERMVLSAFDERRNKYLEEHPSAGKDPKKTGGPIYRRVNGKWMRELILYDKEEIRRIWRQANNGDDATAGLTHMMIWHSNLNDATYQRTRALVRTGMDPRMCSLMQGSTLPRRSGAAGAAVKGVGTMVMELVRMIKRGINDRNFWRGENGRKTRSAYERMCNILKGKFQTAAQKAMMDQVRESRNPGNAEFEDLTFLARSALILRGSVAHKSCLPACVYGPAVASGYDFEREGYSLVGIDPFRLLQNSQVYSLIRPNENPAHKSQLVWMACHSAAFEDLRVLSFIKGTKVVPRGKLSTRGVQIASNENMETMESSTLELRSRYWAIRTRSGGNTNQQRASAGQISVQPTFSVQRNLPFDRTTIMAAFNGNTEGRTSDMRTEIIRMMESARPEDVSFQGRGVFELSDEKAASPIVPSFDMSNEGSYFFGDNAEEYDN",
        "M1": "MSLLTEVETYVLSIVPSGPLKAEIAQRLEDVfAGKNTDLEALMEWLKTRPILSPLTKGILGFVFTLTVPSERGLQRRRFVQNALNGNGDPNNMDKAVKLYRKLKREITFHGAKEISLSYSAGALASCMGLIYNRMGAVTTEVAFGLVCATCEQIADSQHRSHRQMVTTTNPLIRHENRMVLASTTAKAMEQMAGSSEQAAEAMEVASQARQMVQAMRTIGTHPSSSAGLKNDLLENLQAYQKRMGVQMQRFK",
        "M2": "MSLLTEVETPIRNEWGCRCNGSSDPLTIAANIIGILHLTLWILDRLFFKCIYRRFKYGLKRGPSTEGVPESMREEYRKEQQSAVDVDDGHFVNIELE",
        "NS1": "MDSNTVSSFQVDCFLWHVRKRVADQELGDAPFLDRLRRDQKSLRGRGSTLGLDIETATRAGKQIVERILKEESDEALKMTMASVPASRYLTDMTLEEMSRDWFMLMPKQKVTGPLCIRMDQAIMDKNIILKANFSVIFDRLETLILLRAFTEEGAIVGEISPLPSLPGHTDEDVKNAIGVLIGGLEWNDNTVRVSKNLQRFAWRSSNENGGPPLTPKQKRKMARTARSKV",
        "NS2": "MDSNTVSSFQDILMRMSKMQLGSSSEDLNGMVTRLESLKLYRDSLGEAVMRMGDLHSLQNRNEKWREQLGQKFEEIRWLIEEVRHKLKITENSFEQITFMQALQLLLEVEQEIRTFSFQLI"
    }
    
    # Write sequences.json
    with open(os.path.join(API_DIR, "sequences.json"), "w") as f:
        json.dump(sequences, f, indent=2)
    
    # Save metadata.json
    metadata = {
        "last_updated": datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
    }
    with open(os.path.join(API_DIR, "metadata.json"), "w") as f:
        json.dump(metadata, f, indent=2)

    print(f"✅ Generated API files and metadata in {API_DIR}")

if __name__ == "__main__":
    main()
